services:
  - type: web
    plan: free
    name: tradingbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    repo: https://github.com/Sanchit0102/project_09.git
    branch: main
    autoDeploy: True
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_URL
        sync: false
      - key: ADMIN
        sync: false
